@startuml
actor socio
actor atendente

socio -> atendente: informar código
atendente -> atendente: verificar cadastro
alt cadastrado
    atendente -> atendente: verificar pendências
    alt pendências
        atendente -> socio: recusar locação
    else sem pendências
        socio -> atendente: informar cópias
        atendente -> atendente: registrar locação
        atendente -> socio: entregar cópias
    end
else não cadastrado
    atendente -> socio: mensagem de erro
end

atendente -> atendente: manutenção de filmes
atendente -> atendente: registrar novos filmes
atendente -> atendente: confirmar registro
@enduml
