@startuml
actor aluno
actor atendente

aluno -> atendente: solicitar informações
atendente -> aluno: informações sobre cursos

alt interessado em curso
    aluno -> atendente: pedir informações sobre turmas
    atendente -> aluno: informações sobre turmas

    alt horário compatível
        alt não cadastrado
            aluno -> atendente: informar dados
            atendente -> atendente: cadastrar aluno
            atendente -> aluno: confirmação do cadastro
        end

        aluno -> atendente: realizar matrícula
        atendente -> atendente: registrar matrícula
        atendente -> aluno: confirmação da matrícula
    else horário incompatível
        aluno -> atendente: informar incompatibilidade
    end
else não interessado
    aluno -> atendente: agradecer e sair
end
@enduml
