@startuml
actor cliente
participant sistema

cliente -> sistema: selecionar origem e destino
sistema -> cliente: confirmação de origem e destino

cliente -> sistema: selecionar datas
sistema -> cliente: confirmação das datas

cliente -> sistema: consultar voos
sistema -> sistema: buscar horários e preços
sistema -> cliente: horários e preços disponíveis

alt de acordo com horário e preço
    cliente -> sistema: comprar passagens
    sistema -> cliente: selecionar poltronas
    cliente -> sistema: informar pagamento
    sistema -> sistema: processar pagamento
    sistema -> cliente: confirmação da compra
else não de acordo
    cliente -> sistema: cancelar operação
end
@enduml
