DROP DATABASE IF EXISTS LBA2024;
CREATE DATABASE IF NOT EXISTS LBA2024;
USE LBA2024;

CREATE TABLE IF NOT EXISTS SETORES (
    SET_ID INTEGER AUTO_INCREMENT,
    SET_NOME VARCHAR(30) NOT NULL UNIQUE,
    PRIMARY KEY(SET_ID)
);

CREATE TABLE IF NOT EXISTS ATUACOES (
    ATU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ATU_NOME VARCHAR(30) NOT NULL UNIQUE,
    FK_SETORES_SET_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_SETORES_SET_ID) REFERENCES SETORES (SET_ID)
);

CREATE TABLE IF NOT EXISTS CIDADES (
    CID_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CID_ESTADO VARCHAR(2) NOT NULL,
    CID_NOME VARCHAR(30) NOT NULL,
    UNIQUE (CID_ESTADO, CID_NOME)
);

CREATE TABLE IF NOT EXISTS CEPS (
    CEP_ID INTEGER PRIMARY KEY,
    CEP_LOGRADOURO VARCHAR(100) NOT NULL,
    CEP_BAIRRO VARCHAR(30) NOT NULL,
    FK_CIDADES_CID_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CIDADES_CID_ID) REFERENCES CIDADES (CID_ID)
);

CREATE TABLE IF NOT EXISTS EMPRESAS (
    EMP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMP_NOME_FANTASIA VARCHAR(50),
    EMP_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    EMP_SITE VARCHAR(100),
    EMP_EMAIL VARCHAR(100),
    EMP_NUMERO VARCHAR(8),
    EMP_COMPLEMENTO VARCHAR(20),
    EMP_CNPJ VARCHAR(16) NOT NULL UNIQUE,
    FK_ATUACOES_ATU_ID INTEGER NOT NULL,
    FK_CEPS_CEP_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_ATUACOES_ATU_ID) REFERENCES ATUACOES (ATU_ID), 
    FOREIGN KEY (FK_CEPS_CEP_ID) REFERENCES CEPS (CEP_ID)
);

CREATE TABLE IF NOT EXISTS TELEFONES_EMPRESAS (
    TLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    TLE_DDD INTEGER NOT NULL,
    TLE_NUMERO INTEGER NOT NULL,
    FK_EMP_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_EMP_ID) REFERENCES EMPRESAS (EMP_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CARGOS (
    CAR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAR_NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS (
    DEP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEP_NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS COLABORADORES (
    COL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,    
    COL_NOME VARCHAR(100) NOT NULL,
    COL_EMAIL VARCHAR(100),
    FK_EMPRESAS_EMP_ID INTEGER NOT NULL,
    FK_DEPARTAMENTOS_DEP_ID INTEGER NOT NULL,
    FK_CARGOS_CAR_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_EMPRESAS_EMP_ID) REFERENCES EMPRESAS (EMP_ID),
    FOREIGN KEY (FK_DEPARTAMENTOS_DEP_ID) REFERENCES DEPARTAMENTOS (DEP_ID),
    FOREIGN KEY (FK_CARGOS_CAR_ID) REFERENCES CARGOS (CAR_ID)    
);

CREATE TABLE IF NOT EXISTS TELEFONES_COLABORADORES (
    TLC_ID INT AUTO_INCREMENT PRIMARY KEY,
    TLC_DDD INTEGER NOT NULL,
    TLC_NUMERO INTEGER NOT NULL,
    FK_COL_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_COL_ID) REFERENCES COLABORADORES (COL_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
    FOR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FOR_SITE VARCHAR(100),
    FOR_EMAIL VARCHAR(100),
    FOR_NOME_FANTASIA VARCHAR(50),
    FOR_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    FOR_CNPJ VARCHAR(16) NOT NULL UNIQUE,
    FK_CEPS_CEP_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CEPS_CEP_ID) REFERENCES CEPS (CEP_ID)
);

CREATE TABLE IF NOT EXISTS TELEFONES_FORNECEDORES (
    TLF_ID INT AUTO_INCREMENT PRIMARY KEY,
    TLF_NUMERO INTEGER NOT NULL,
    TLF_DDD INTEGER NOT NULL,
    FK_FOR_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_FOR_ID) REFERENCES FORNECEDORES (FOR_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SERVICOS (
    SER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SER_NOME VARCHAR(100) NOT NULL,
    SER_CUSTO DECIMAL(10,2) NOT NULL,
    FK_FORNECEDORES_FOR_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_FORNECEDORES_FOR_ID) REFERENCES FORNECEDORES (FOR_ID)
);

CREATE TABLE IF NOT EXISTS EVENTOS (
    EVE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EVE_NOME VARCHAR(150) NOT NULL,
    EVE_DATA DATE NOT NULL,
    EVE_HORA TIME NOT NULL,
    EVE_CUSTO_TOTAL DECIMAL(10,2) NOT NULL DEFAULT 0.0
);

CREATE TABLE IF NOT EXISTS SERVICOS_EVENTOS (
    SVE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SVE_VALOR DECIMAL(10,2) NOT NULL,
    FK_SERVICOS_SER_ID INTEGER NOT NULL,
    FK_EVENTOS_EVE_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_SERVICOS_SER_ID) REFERENCES SERVICOS (SER_ID),
    FOREIGN KEY (FK_EVENTOS_EVE_ID) REFERENCES EVENTOS (EVE_ID)   
);

CREATE TABLE IF NOT EXISTS COLABORADORES_EVENTOS (
    CEV_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_COLABORADORES_COL_ID INTEGER NOT NULL,
    FK_EVENTOS_EVE_ID INTEGER NOT NULL,
    FOREIGN KEY(FK_COLABORADORES_COL_ID) REFERENCES COLABORADORES (COL_ID),
    FOREIGN KEY(FK_EVENTOS_EVE_ID) REFERENCES EVENTOS (EVE_ID)
);

INSERT INTO SETORES (SET_NOME) VALUES 
('AUTOMOBILISTICO'), 
('FARMACEUTICO'), 
('INDUSTRIAL');

INSERT INTO ATUACOES (ATU_NOME, FK_SETORES_SET_ID) VALUES
('CONCESSIONARIA', 1),
('FARMACIA', 2),
('METALURGICA', 3);

INSERT INTO CIDADES (CID_ESTADO, CID_NOME) VALUES
('SP', 'SÃO PAULO'),
('SP', 'SÃO JOÃO DA BOA VISTA'),
('SC', 'ITAJAI');

INSERT INTO CEPS (CEP_ID, CEP_LOGRADOURO, CEP_BAIRRO, FK_CIDADES_CID_ID) VALUES
(123456789, 'RUA SAO PAULO, 12', 'BAIRRO SP', 1),
(987654321, 'RUA JOANENSE, 12', 'BAIRRO SJ', 2),
(918237645, 'RUA DO SUL, 12', 'BAIRRO DO SUL', 3);

INSERT INTO EMPRESAS (EMP_NOME_FANTASIA, EMP_RAZAO_SOCIAL, EMP_SITE, EMP_EMAIL, EMP_NUMERO, EMP_COMPLEMENTO,
 EMP_CNPJ, FK_ATUACOES_ATU_ID, FK_CEPS_CEP_ID) VALUES
 ('CONCESSIONARIA PAULISTA', 'RAZAO SOCIAL X', 'WWW.EMPRESAPAULISTA.COM.BR', 'CONCESSIONARIA@SP.COM', '23', 'CASA A',
 '1233211111', 1, 123456789),
 ('FARMACIA JOANENSE', 'RAZAO SOCIAL Y', 'WWW.EMPRESAJOANENSE.COM.BR', 'FARMACIA@SJ.COM', '323', 'CASA B',
 '1233211112', 2, 987654321),
 ('METALURGICA SUL', 'RAZAO SOCIAL Z', 'WWW.EMPRESASUL.COM.BR', 'METALURGICA@SUL.COM', '13', 'CASA C',
 '1233211113', 3, 918237645);
 
INSERT INTO TELEFONES_EMPRESAS (TLE_DDD, TLE_NUMERO, FK_EMP_ID) VALUES
(011, 1233212, 1),
(019, 1233212, 2),
(047, 1233212, 3);
 
 INSERT INTO CARGOS (CAR_NOME) VALUES
 ('CHEFE'),
 ('FUNCIONARIO'),
 ('ESTAGIÁRIO');
 
 INSERT INTO DEPARTAMENTOS (DEP_NOME) VALUES
 ('DEPARTAMENTO 1'),
 ('DEPARTAMENTO 2'),
 ('DEPARTAMENTO 3');
 
INSERT INTO COLABORADORES (COL_NOME, COL_EMAIL, FK_EMPRESAS_EMP_ID, FK_DEPARTAMENTOS_DEP_ID, FK_CARGOS_CAR_ID) VALUES
('JOÃO SILVA', 'JOAO.SILVA@EMPRESA.COM', 1, 1, 1),
('MARIA SOUZA', 'MARIA.SOUZA@EMPRESA.COM', 2, 2, 2),
('CARLOS LIMA', 'CARLOS.LIMA@EMPRESA.COM', 3, 3, 3);

INSERT INTO TELEFONES_COLABORADORES (TLC_DDD, TLC_NUMERO, FK_COL_ID) VALUES
(011, 999999999, 1),
(019, 888888888, 2),
(047, 777777777, 3);

INSERT INTO FORNECEDORES (FOR_SITE, FOR_EMAIL, FOR_NOME_FANTASIA, FOR_RAZAO_SOCIAL, FOR_CNPJ, FK_CEPS_CEP_ID) VALUES
('WWW.FORNECEDOR1.COM.BR', 'CONTATO@FORNECEDOR1.COM', 'FORNECEDOR 1', 'FORNECEDOR 1', '12222222', 123456789),
('WWW.FORNECEDOR2.COM.BR', 'CONTATO@FORNECEDOR2.COM', 'FORNECEDOR 2', 'FORNECEDOR 2', '23333333', 918237645),
('WWW.FORNECEDOR3.COM.BR', 'CONTATO@FORNECEDOR3.COM', 'FORNECEDOR 3', 'FORNECEDOR 3', '34444444', 987654321);

INSERT INTO TELEFONES_FORNECEDORES (TLF_DDD, TLF_NUMERO, FK_FOR_ID) VALUES
(011, 555555555, 1),
(019, 444444444, 2),
(047, 333333333, 3);

INSERT INTO SERVICOS (SER_NOME, SER_CUSTO, FK_FORNECEDORES_FOR_ID) VALUES
('SERVIÇO DE TRANSPORTE', 1000.50, 1),
('SERVIÇO DE LIMPEZA', 500.00, 2),
('SERVIÇO DE MANUTENÇÃO', 750.75, 3);

INSERT INTO EVENTOS (EVE_NOME, EVE_DATA, EVE_HORA, EVE_CUSTO_TOTAL) VALUES
('EVENTO CORPORATIVO', '2024-05-15', '10:00:00', 2500.00),
('REUNIÃO ANUAL', '2024-06-20', '14:00:00', 3000.00),
('WORKSHOP TÉCNICO', '2024-07-10', '09:00:00', 1500.00);

INSERT INTO SERVICOS_EVENTOS (SVE_VALOR, FK_SERVICOS_SER_ID, FK_EVENTOS_EVE_ID) VALUES
(1000.50, 1, 1),
(500.00, 2, 2),
(750.75, 3, 3);

INSERT INTO COLABORADORES_EVENTOS (FK_COLABORADORES_COL_ID, FK_EVENTOS_EVE_ID) VALUES
(1, 1),
(2, 2),
(3, 3);

UPDATE CEPS 
SET CEP_BAIRRO = 'Jardim Ypê'
WHERE CEP_BAIRRO = 'Vila Ypê' 
AND CEP_ID BETWEEN 13876600 AND 13876609;

UPDATE EVENTOS
SET EVE_DATA = '2024-11-20'
WHERE EVE_DATA = '2024-11-10';

UPDATE COLABORADORES
SET FK_DEPARTAMENTOS_DEP_ID = 3, FK_CARGOS_CAR_ID = 1
WHERE COL_NOME = 'Ana Souza';

DELETE FROM COLABORADORES
WHERE COL_EMAIL LIKE '%@uol%';



 
 
 
 
 
 
 
 
 
 
 
