@startuml
actor advogado
participant sistema

advogado -> sistema: cadastrar cliente e parte contrária
sistema -> advogado: confirmação de cadastro

advogado -> sistema: registrar processo
sistema -> advogado: confirmação de registro

advogado -> sistema: registrar audiências
sistema -> sistema: salvar informações
sistema -> advogado: registro no histórico

advogado -> sistema: gerar relatórios
sistema -> advogado: relatório de situação

advogado -> sistema: controlar contas
sistema -> advogado: controle de contas atualizado
@enduml
